openapi: 3.0.0
info:
  title: HF API
  description: OpenAPI specification for the Hack Forums API.
  version: 2.0.0
servers:
  - url: "https://hackforums.net/api/v2"
    description: HF API Version 2
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /read/bratings:
    $ref: paths\read@bratings.yaml
  /read/bytes:
    $ref: paths\read@bytes.yaml
  /read/contracts:
    $ref: paths\read@contracts.yaml
  /read/disputes:
    $ref: paths\read@disputes.yaml
  /read/forums:
    $ref: paths\read@forums.yaml
  /read/me:
    $ref: paths\read@me.yaml
  /read/posts:
    $ref: paths\read@posts.yaml
  /read/sigmarket-market:
    $ref: paths\read@sigmarketMarket.yaml
  /read/sigmarket-order:
    $ref: paths\read@sigmarketOrder.yaml
  /read/threads:
    $ref: paths\read@threads.yaml
  /read/users:
    $ref: paths\read@users.yaml
